#!/bin/sh
#
# soes        Starts soes.
#

start() {
	printf "Starting soes: "
	/usr/sbin/soes-demo &
	touch /var/lock/soes-demo
	echo "OK"
}
stop() {
	printf "Stopping soes: "
	killall soes-demo
	rm -f /var/lock/soes-demo
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


